name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run Playwright tests on Docker
      run: docker run -v local_reports_volume:/app/playwright-report playwright-tests && docker cp playwright-tests:/app/playwright-report .

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
